CREATE TABLE books (
id SERIAL PRIMARY KEY,
title VARCHAR(255) NOT NULL,
author VARCHAR(255) NOT NULL,
isbn VARCHAR(255) UNIQUE,
publication_year INTEGER,
category VARCHAR(50),
total_copies INTEGER DEFAULT 1,
available_copies INTEGER DEFAULT 1,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CHECK (available_copies >= 0)
);

CREATE TABLE members (
id SERIAL PRIMARY KEY,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
phone VARCHAR(100),
membership_date DATE DEFAULT CURRENT_DATE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE loans (
id SERIAL PRIMARY KEY,
book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
loan_date DATE DEFAULT CURRENT_DATE,
due_date DATE NOT NULL,
return_date DATE NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CHECK (due_date > loan_date)
);

